# Generated by Django 2.1.1 on 2018-09-21 13:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bimestre', models.CharField(max_length=50, verbose_name='Bimestre')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoProgramatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=50)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina e Professor',
                'verbose_name_plural': 'Disciplinas e Professores',
            },
        ),
        migrations.CreateModel(
            name='ObjetivosEspecificos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='topicos')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ementa', ckeditor.fields.RichTextField(verbose_name='Ementa')),
                ('objetivos_gerais', ckeditor.fields.RichTextField(verbose_name='Objetivos Gerais da Disciplina')),
                ('objetivos_especificos', ckeditor.fields.RichTextField(verbose_name='Objetivos Especficos da Disciplina')),
                ('conteudo_programatico', ckeditor.fields.RichTextField(verbose_name='Conteúdo Programático')),
                ('metodologia', ckeditor.fields.RichTextField(verbose_name='Metologia')),
                ('recursos_didaticos', ckeditor.fields.RichTextField(verbose_name='Recursos Didáticos')),
                ('sistema_de_avaliacao', ckeditor.fields.RichTextField(verbose_name='Sistema de Avaliação')),
                ('referencias_basicas', ckeditor.fields.RichTextField(verbose_name='Referências Básicas')),
                ('referencias_complementares', ckeditor.fields.RichTextField(verbose_name='Referências Complementares')),
                ('disciplinaProfessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaProfessor', verbose_name='Disciplina Ministrada')),
            ],
            options={
                'verbose_name': 'Plano de Disciplina',
                'verbose_name_plural': 'Planos de Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor(a)',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50, verbose_name='texto')),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bimestre')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bimestres', to='core.PlanoDisciplina')),
            ],
        ),
        migrations.AddField(
            model_name='objetivosespecificos',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='core.PlanoDisciplina'),
        ),
        migrations.AddField(
            model_name='disciplinaprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.Professor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo', to='core.PlanoDisciplina'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bimestre'),
        ),
        migrations.AddField(
            model_name='bimestre',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bime', to='core.PlanoDisciplina'),
        ),
    ]
